### ISSUE TITLE
Unable to compile v0.9 with Arduino Nano as target

### ISSUE THREAD

**Issue by barrenechea** [ShendoXT/memcarduino#39]
Hi! Thank you for this awesome project!
I was attempting to update a device I got from AliExpress, and I was unable to compile the project on v0.9 with Arduino Nano as target, getting the following errors:

```
/private/var/folders/7w/dck_kxd55fl0bvyp5fkzv1rh0000gn/T/.arduinoIDE-unsaved2024828-48222-w4ka1e.iq5wn/sketch_sep28a/sketch_sep28a.ino: In function 'byte SoftTransfer(byte)':
/private/var/folders/7w/dck_kxd55fl0bvyp5fkzv1rh0000gn/T/.arduinoIDE-unsaved2024828-48222-w4ka1e.iq5wn/sketch_sep28a/sketch_sep28a.ino:145:22: error: 'CmndPin' was not declared in this scope
         digitalWrite(CmndPin, !!(data & (1 << i)));
                      ^~~~~~~
/private/var/folders/7w/dck_kxd55fl0bvyp5fkzv1rh0000gn/T/.arduinoIDE-unsaved2024828-48222-w4ka1e.iq5wn/sketch_sep28a/sketch_sep28a.ino:148:22: error: 'ClockPin' was not declared in this scope
         digitalWrite(ClockPin, LOW);
                      ^~~~~~~~
/private/var/folders/7w/dck_kxd55fl0bvyp5fkzv1rh0000gn/T/.arduinoIDE-unsaved2024828-48222-w4ka1e.iq5wn/sketch_sep28a/sketch_sep28a.ino:148:22: note: suggested alternative: 'AckPin'
         digitalWrite(ClockPin, LOW);
```

Just to note that I was successfully able to program v0.8 and read a memory card 😄

**Comment by ShendoXT** [comment]
Oops, my bad. Can you try it now? Should be fixed with the latest commit.

Also, how are you satisfied with that AliExpress adapter? Are you using 1st or 3rd party memory cards?

**Comment by barrenechea** [comment]
Fixed! Thank you very much!

And the adaptor has been working fine so far! It uses the same pinout you've defined, so the stock .ino file works flawlessly. It comes with v0.4 (never used it on that version), and the soldering job on it looks pretty decent. Although the 3D-printed case is not the highest quality (mine does not fully close), it is just a cosmetic thing. I've been testing with a 1st party and with a PicoMemcard 😄


<details>
  <summary>Some pictures for reference</summary>
  
  
![A318A44B-0063-4851-AEF8-FF1542084EF9_1_102_o](https://github.com/user-attachments/assets/ac103a22-0c3e-4ac2-8d94-92096efe9d6c)
![94DCB600-3975-42E5-BC51-C89FF0D22D18_1_102_o](https://github.com/user-attachments/assets/89671801-d742-46b0-aace-76351261290a)
![F7E0F005-1A1D-4C10-B955-87AA0238F043_1_102_o](https://github.com/user-attachments/assets/9e2cdc88-b9a5-44ad-b904-26de7b628073)
![4160C5AA-C17F-4BD7-8D67-E98975EAC673_1_102_o](https://github.com/user-attachments/assets/c3266610-d0ca-4672-b5bc-c5e76be7514b)

</details>

It came with the new bootloader, so flashing it was pretty straightforward.

**Comment by ShendoXT** [comment]
Awesome. Glad to see that it's working. Thanks for the pictures also. That adaptor looks neat.
I think I know why they left the controller port also.
Looks like they are repurposing connectors from 3rd party PS2 multitaps.

![31zX7-yWAmL](https://github.com/user-attachments/assets/b2fa9e35-d7a2-418b-918d-2757f996e871)

Shame that they didn't go with Arduino Micro. It can be used as a HID gamepad.
So the adapter would read Memory Cards with MemcardRex and adapt PS1 and PS2 controllers to PC over USB.
Missed opportunity on their part I must say.

As for pullups, yeah. PS1 has 1K pullups and is able to do 250k clock.
I wanted MemCARDuino to be as straightforward as possible so I used the internal pullups (10K) but had to drop the speed
because otherwise I was getting read/write errors. No big deal, as long as it works :).
